<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    public function run()
    {
        // Districts
        $districts = [
            // Andhra Pradesh
            ['name' => 'Anantapur', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'Chittoor', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'East Godavari', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'Guntur', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'Krishna', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'Kurnool', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'Nellore', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'Prakasam', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'Srikakulam', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'Visakhapatnam', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'Vizianagaram', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'West Godavari', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            ['name' => 'YSR Kadapa', 'state_id' => $this->getStateId('Andhra Pradesh')] ,
            // Arunachal Pradesh
            ['name' => 'Tawang', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'West Kameng', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'East Kameng', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Papum Pare', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Kurung Kumey', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Kra Daadi', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Lower Subansiri', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Upper Subansiri', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'West Siang', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'East Siang', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Siang', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Upper Siang', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Lower Siang', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Lower Dibang Valley', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Dibang Valley', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Anjaw', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Lohit', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Namsai', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Changlang', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Tirap', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            ['name' => 'Longding', 'state_id' => $this->getStateId('Arunachal Pradesh')] ,
            // Assam
            ['name' => 'Baksa', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Barpeta', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Biswanath', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Bongaigaon', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Cachar', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Charaideo', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Chirang', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Darrang', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Dhemaji', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Dhubri', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Dibrugarh', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Goalpara', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Golaghat', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Hailakandi', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Hojai', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Jorhat', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Kamrup Metropolitan', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Kamrup', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Karbi Anglong', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Karimganj', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Kokrajhar', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Lakhimpur', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Majuli', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Morigaon', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Nagaon', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Nalbari', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Dima Hasao', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Sivasagar', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Sonitpur', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'South Salmara-Mankachar', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Tinsukia', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'Udalguri', 'state_id' => $this->getStateId('Assam')] ,
            ['name' => 'West Karbi Anglong', 'state_id' => $this->getStateId('Assam')] ,
            // Bihar
            ['name' => 'Araria', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Arwal', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Aurangabad', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Banka', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Begusarai', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Bhagalpur', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Bhojpur', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Buxar', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Darbhanga', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'East Champaran (Motihari)', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Gaya', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Gopalganj', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Jamui', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Jehanabad', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Kaimur (Bhabua)', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Katihar', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Khagaria', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Kishanganj', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Lakhisarai', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Madhepura', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Madhubani', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Munger (Monghyr)', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Muzaffarpur', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Nalanda', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Nawada', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Patna', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Purnia (Purnea)', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Rohtas', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Saharsa', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Samastipur', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Saran', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Sheikhpura', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Sheohar', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Sitamarhi', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Siwan', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Supaul', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'Vaishali', 'state_id' => $this->getStateId('Bihar')] ,
            ['name' => 'West Champaran', 'state_id' => $this->getStateId('Bihar')] ,
            // Chandigarh (UT)
            ['name' => 'Chandigarh', 'state_id' => $this->getStateId('Chandigarh')] ,
            // Chhattisgarh
            ['name' => 'Balod', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Baloda Bazar', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Balrampur', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Bastar', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Bemetara', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Bijapur', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Bilaspur', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Dantewada (South Bastar)', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Dhamtari', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Durg', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Gariyaband', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Janjgir-Champa', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Jashpur', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Kabirdham (Kawardha)', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Kanker (North Bastar)', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Kondagaon', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Korba', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Korea (Koriya)', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Mahasamund', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Mungeli', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Narayanpur', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Raigarh', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Raipur', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Rajnandgaon', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Sukma', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Surajpur', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            ['name' => 'Surguja', 'state_id' => $this->getStateId('Chhattisgarh')] ,
            // Dadra and Nagar Haveli (UT)
            ['name' => 'Dadra & Nagar Haveli', 'state_id' => $this->getStateId('Dadra and Nagar Haveli')] ,
            // Daman and Diu (UT)
            ['name' => 'Daman', 'state_id' => $this->getStateId('Daman and Diu')] ,
            ['name' => 'Diu', 'state_id' => $this->getStateId('Daman and Diu')] ,
            // Delhi (NCT)
            ['name' => 'Central Delhi', 'state_id' => $this->getStateId('Delhi')] ,
            ['name' => 'East Delhi', 'state_id' => $this->getStateId('Delhi')] ,
            ['name' => 'New Delhi', 'state_id' => $this->getStateId('Delhi')] ,
            ['name' => 'North Delhi', 'state_id' => $this->getStateId('Delhi')] ,
            ['name' => 'North East  Delhi', 'state_id' => $this->getStateId('Delhi')] ,
            ['name' => 'North West  Delhi', 'state_id' => $this->getStateId('Delhi')] ,
            ['name' => 'Shahdara', 'state_id' => $this->getStateId('Delhi')] ,
            ['name' => 'South Delhi', 'state_id' => $this->getStateId('Delhi')] ,
            ['name' => 'South East Delhi', 'state_id' => $this->getStateId('Delhi')] ,
            ['name' => 'South West  Delhi', 'state_id' => $this->getStateId('Delhi')] ,
            ['name' => 'West Delhi', 'state_id' => $this->getStateId('Delhi')] ,
            // Goa
            ['name' => 'North Goa', 'state_id' => $this->getStateId('Goa')] ,
            ['name' => 'South Goa', 'state_id' => $this->getStateId('Goa')] ,
            // Gujarat
            ['name' => 'Ahmedabad', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Amreli', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Anand', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Aravalli', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Banaskantha (Palanpur)', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Bharuch', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Bhavnagar', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Botad', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Chhota Udepur', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Dahod', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Dangs (Ahwa)', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Devbhoomi Dwarka', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Gandhinagar', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Gir Somnath', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Jamnagar', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Junagadh', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Kachchh', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Kheda (Nadiad)', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Mahisagar', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Mehsana', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Morbi', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Narmada (Rajpipla)', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Navsari', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Panchmahal (Godhra)', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Patan', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Porbandar', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Rajkot', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Sabarkantha (Himmatnagar)', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Surat', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Surendranagar', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Tapi (Vyara)', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Vadodara', 'state_id' => $this->getStateId('Gujarat')] ,
            ['name' => 'Valsad', 'state_id' => $this->getStateId('Gujarat')] ,
            // Haryana
            ['name' => 'Ambala', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Bhiwani', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Charkhi Dadri', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Faridabad', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Fatehabad', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Gurgaon', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Hisar', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Jhajjar', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Jind', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Kaithal', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Karnal', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Kurukshetra', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Mahendragarh', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Mewat', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Palwal', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Panchkula', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Panipat', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Rewari', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Rohtak', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Sirsa', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Sonipat', 'state_id' => $this->getStateId('Haryana')] ,
            ['name' => 'Yamunanagar', 'state_id' => $this->getStateId('Haryana')] ,
            // Himachal Pradesh
            ['name' => 'Bilaspur', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Chamba', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Hamirpur', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Kangra', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Kinnaur', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Kullu', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Lahaul &amp; Spiti', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Mandi', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Shimla', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Sirmaur (Sirmour)', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Solan', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            ['name' => 'Una', 'state_id' => $this->getStateId('Himachal Pradesh')] ,
            // Jammu and Kashmir
            ['name' => 'Anantnag', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Bandipore', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Baramulla', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Budgam', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Doda', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Ganderbal', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Jammu', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Kargil', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Kathua', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Kishtwar', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Kulgam', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Kupwara', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Leh', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Poonch', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Pulwama', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Rajouri', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Ramban', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Reasi', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Samba', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Shopian', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Srinagar', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            ['name' => 'Udhampur', 'state_id' => $this->getStateId('Jammu and Kashmir')] ,
            // Jharkhand
            ['name' => 'Bokaro', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Chatra', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Deoghar', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Dhanbad', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Dumka', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'East Singhbhum', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Garhwa', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Giridih', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Godda', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Gumla', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Hazaribag', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Jamtara', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Khunti', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Koderma', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Latehar', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Lohardaga', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Pakur', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Palamu', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Ramgarh', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Ranchi', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Sahibganj', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Seraikela-Kharsawan', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'Simdega', 'state_id' => $this->getStateId('Jharkhand')] ,
            ['name' => 'West Singhbhum', 'state_id' => $this->getStateId('Jharkhand')] ,
            // Karnataka
            ['name' => 'Bagalkot', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Ballari (Bellary)', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Belagavi (Belgaum)', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Bengaluru (Bangalore) Rural', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Bengaluru (Bangalore) Urban', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Bidar', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Chamarajanagar', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Chikballapur', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Chikkamagaluru (Chikmagalur)', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Chitradurga', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Dakshina Kannada', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Davangere', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Dharwad', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Gadag', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Hassan', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Haveri', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Kalaburagi (Gulbarga)', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Kodagu', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Kolar', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Koppal', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Mandya', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Mysuru (Mysore)', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Raichur', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Ramanagara', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Shivamogga (Shimoga)', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Tumakuru (Tumkur)', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Udupi', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Uttara Kannada (Karwar)', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Vijayapura (Bijapur)', 'state_id' => $this->getStateId('Karnataka')] ,
            ['name' => 'Yadgir', 'state_id' => $this->getStateId('Karnataka')] ,
            // Kerala
            ['name' => 'Alappuzha', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Ernakulam', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Idukki', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Kannur', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Kasaragod', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Kollam', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Kottayam', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Kozhikode', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Malappuram', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Palakkad', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Pathanamthitta', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Thiruvananthapuram', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Thrissur', 'state_id' => $this->getStateId('Kerala')] ,
            ['name' => 'Wayanad', 'state_id' => $this->getStateId('Kerala')] ,
            // Lakshadweep (UT)
            ['name' => 'Agatti', 'state_id' => $this->getStateId('Lakshadweep')] ,
            ['name' => 'Amini', 'state_id' => $this->getStateId('Lakshadweep')] ,
            ['name' => 'Androth', 'state_id' => $this->getStateId('Lakshadweep')] ,
            ['name' => 'Bithra', 'state_id' => $this->getStateId('Lakshadweep')] ,
            ['name' => 'Chethlath', 'state_id' => $this->getStateId('Lakshadweep')] ,
            ['name' => 'Kavaratti', 'state_id' => $this->getStateId('Lakshadweep')] ,
            ['name' => 'Kadmath', 'state_id' => $this->getStateId('Lakshadweep')] ,
            ['name' => 'Kalpeni', 'state_id' => $this->getStateId('Lakshadweep')] ,
            ['name' => 'Kilthan', 'state_id' => $this->getStateId('Lakshadweep')] ,
            ['name' => 'Minicoy', 'state_id' => $this->getStateId('Lakshadweep')] ,
            // Madhya Pradesh
            ['name' => 'Agar Malwa', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Alirajpur', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Anuppur', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Ashoknagar', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Balaghat', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Barwani', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Betul', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Bhind', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Bhopal', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Burhanpur', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Chhatarpur', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Chhindwara', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Damoh', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Datia', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Dewas', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Dhar', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Dindori', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Guna', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Gwalior', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Harda', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Hoshangabad', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Indore', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Jabalpur', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Jhabua', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Katni', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Khandwa', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Khargone', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Mandla', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Mandsaur', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Morena', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Narsinghpur', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Neemuch', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Panna', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Raisen', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Rajgarh', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Ratlam', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Rewa', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Sagar', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Satna', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Sehore', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Seoni', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Shahdol', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Shajapur', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Sheopur', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Shivpuri', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Sidhi', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Singrauli', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Tikamgarh', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Ujjain', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Umaria', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            ['name' => 'Vidisha', 'state_id' => $this->getStateId('Madhya Pradesh')] ,
            // Maharashtra
            ['name' => 'Ahmednagar', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Akola', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Amravati', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Aurangabad', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Beed', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Bhandara', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Buldhana', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Chandrapur', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Dhule', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Gadchiroli', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Gondia', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Hingoli', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Jalgaon', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Jalna', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Kolhapur', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Latur', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Mumbai City', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Mumbai Suburban', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Nagpur', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Nanded', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Nandurbar', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Nashik', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Osmanabad', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Palghar', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Parbhani', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Pune', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Raigad', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Ratnagiri', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Sangli', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Satara', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Sindhudurg', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Solapur', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Thane', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Wardha', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Washim', 'state_id' => $this->getStateId('Maharashtra')] ,
            ['name' => 'Yavatmal', 'state_id' => $this->getStateId('Maharashtra')] ,
            // Manipur
            ['name' => 'Bishnupur', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Chandel', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Churachandpur', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Imphal East', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Imphal West', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Jiribam', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Kakching', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Kamjong', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Kangpokpi', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Noney', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Pherzawl', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Senapati', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Tamenglong', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Tengnoupal', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Thoubal', 'state_id' => $this->getStateId('Manipur')] ,
            ['name' => 'Ukhrul', 'state_id' => $this->getStateId('Manipur')] ,
            // Meghalaya
            ['name' => 'East Garo Hills', 'state_id' => $this->getStateId('Meghalaya')] ,
            ['name' => 'East Jaintia Hills', 'state_id' => $this->getStateId('Meghalaya')] ,
            ['name' => 'East Khasi Hills', 'state_id' => $this->getStateId('Meghalaya')] ,
            ['name' => 'North Garo Hills', 'state_id' => $this->getStateId('Meghalaya')] ,
            ['name' => 'Ri Bhoi', 'state_id' => $this->getStateId('Meghalaya')] ,
            ['name' => 'South Garo Hills', 'state_id' => $this->getStateId('Meghalaya')] ,
            ['name' => 'South West Garo Hills', 'state_id' => $this->getStateId('Meghalaya')] ,
            ['name' => 'South West Khasi Hills', 'state_id' => $this->getStateId('Meghalaya')] ,
            ['name' => 'West Garo Hills', 'state_id' => $this->getStateId('Meghalaya')] ,
            ['name' => 'West Jaintia Hills', 'state_id' => $this->getStateId('Meghalaya')] ,
            ['name' => 'West Khasi Hills', 'state_id' => $this->getStateId('Meghalaya')] ,
            // Mizoram
            ['name' => 'Aizawl', 'state_id' => $this->getStateId('Mizoram')] ,
            ['name' => 'Champhai', 'state_id' => $this->getStateId('Mizoram')] ,
            ['name' => 'Kolasib', 'state_id' => $this->getStateId('Mizoram')] ,
            ['name' => 'Lawngtlai', 'state_id' => $this->getStateId('Mizoram')] ,
            ['name' => 'Lunglei', 'state_id' => $this->getStateId('Mizoram')] ,
            ['name' => 'Mamit', 'state_id' => $this->getStateId('Mizoram')] ,
            ['name' => 'Saiha', 'state_id' => $this->getStateId('Mizoram')] ,
            ['name' => 'Serchhip', 'state_id' => $this->getStateId('Mizoram')] ,
            // Nagaland
            ['name' => 'Dimapur', 'state_id' => $this->getStateId('Nagaland')] ,
            ['name' => 'Kiphire', 'state_id' => $this->getStateId('Nagaland')] ,
            ['name' => 'Kohima', 'state_id' => $this->getStateId('Nagaland')] ,
            ['name' => 'Longleng', 'state_id' => $this->getStateId('Nagaland')] ,
            ['name' => 'Mokokchung', 'state_id' => $this->getStateId('Nagaland')] ,
            ['name' => 'Mon', 'state_id' => $this->getStateId('Nagaland')] ,
            ['name' => 'Peren', 'state_id' => $this->getStateId('Nagaland')] ,
            ['name' => 'Phek', 'state_id' => $this->getStateId('Nagaland')] ,
            ['name' => 'Tuensang', 'state_id' => $this->getStateId('Nagaland')] ,
            ['name' => 'Wokha', 'state_id' => $this->getStateId('Nagaland')] ,
            ['name' => 'Zunheboto', 'state_id' => $this->getStateId('Nagaland')] ,
            // Odisha
            ['name' => 'Angul', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Balangir', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Balasore', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Bargarh', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Bhadrak', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Boudh', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Cuttack', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Deogarh', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Dhenkanal', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Gajapati', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Ganjam', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Jagatsinghapur', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Jajpur', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Jharsuguda', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Kalahandi', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Kandhamal', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Kendrapara', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Kendujhar (Keonjhar)', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Khordha', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Koraput', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Malkangiri', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Mayurbhanj', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Nabarangpur', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Nayagarh', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Nuapada', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Puri', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Rayagada', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Sambalpur', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Sonepur', 'state_id' => $this->getStateId('Odisha')] ,
            ['name' => 'Sundargarh', 'state_id' => $this->getStateId('Odisha')] ,
            // Puducherry (UT)
            ['name' => 'Karaikal', 'state_id' => $this->getStateId('Puducherry')] ,
            ['name' => 'Mahe', 'state_id' => $this->getStateId('Puducherry')] ,
            ['name' => 'Pondicherry', 'state_id' => $this->getStateId('Puducherry')] ,
            ['name' => 'Yanam', 'state_id' => $this->getStateId('Puducherry')] ,
            // Punjab
            ['name' => 'Amritsar', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Barnala', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Bathinda', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Faridkot', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Fatehgarh Sahib', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Fazilka', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Ferozepur', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Gurdaspur', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Hoshiarpur', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Jalandhar', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Kapurthala', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Ludhiana', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Mansa', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Moga', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Muktsar', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Nawanshahr (Shahid Bhagat Singh Nagar)', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Pathankot', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Patiala', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Rupnagar', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Sahibzada Ajit Singh Nagar (Mohali)', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Sangrur', 'state_id' => $this->getStateId('Punjab')] ,
            ['name' => 'Tarn Taran', 'state_id' => $this->getStateId('Punjab')] ,
            // Rajasthan
            ['name' => 'Ajmer', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Alwar', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Banswara', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Baran', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Barmer', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Bharatpur', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Bhilwara', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Bikaner', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Bundi', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Chittorgarh', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Churu', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Dausa', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Dholpur', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Dungarpur', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Hanumangarh', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Jaipur', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Jaisalmer', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Jalore', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Jhalawar', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Jhunjhunu', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Jodhpur', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Karauli', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Kota', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Nagaur', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Pali', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Pratapgarh', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Rajsamand', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Sawai Madhopur', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Sikar', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Sirohi', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Sri Ganganagar', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Tonk', 'state_id' => $this->getStateId('Rajasthan')] ,
            ['name' => 'Udaipur', 'state_id' => $this->getStateId('Rajasthan')] ,
            // Sikkim
            ['name' => 'East Sikkim', 'state_id' => $this->getStateId('Sikkim')] ,
            ['name' => 'North Sikkim', 'state_id' => $this->getStateId('Sikkim')] ,
            ['name' => 'South Sikkim', 'state_id' => $this->getStateId('Sikkim')] ,
            ['name' => 'West Sikkim', 'state_id' => $this->getStateId('Sikkim')] ,
            // Tamil Nadu
            ['name' => 'Ariyalur', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Chennai', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Coimbatore', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Cuddalore', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Dharmapuri', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Dindigul', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Erode', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Kanchipuram', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Kanyakumari', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Karur', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Krishnagiri', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Madurai', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Nagapattinam', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Namakkal', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Nilgiris', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Perambalur', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Pudukkottai', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Ramanathapuram', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Salem', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Sivaganga', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Thanjavur', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Theni', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Thoothukudi (Tuticorin)', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Tiruchirappalli', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Tirunelveli', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Tiruppur', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Tiruvallur', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Tiruvannamalai', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Tiruvarur', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Vellore', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Viluppuram', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            ['name' => 'Virudhunagar', 'state_id' => $this->getStateId('Tamil Nadu')] ,
            // Telangana
            ['name' => 'Adilabad', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Bhadradri Kothagudem', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Hyderabad', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Jagtial', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Jangaon', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Jayashankar Bhoopalpally', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Jogulamba Gadwal', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Kamareddy', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Karimnagar', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Khammam', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Komaram Bheem Asifabad', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Mahabubabad', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Mahabubnagar', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Mancherial', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Medak', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Medchal', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Nagarkurnool', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Nalgonda', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Nirmal', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Nizamabad', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Peddapalli', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Rajanna Sircilla', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Rangareddy', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Sangareddy', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Siddipet', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Suryapet', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Vikarabad', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Wanaparthy', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Warangal (Rural)', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Warangal (Urban)', 'state_id' => $this->getStateId('Telangana')] ,
            ['name' => 'Yadadri Bhuvanagiri', 'state_id' => $this->getStateId('Telangana')] ,
            // Tripura
            ['name' => 'Dhalai', 'state_id' => $this->getStateId('Tripura')] ,
            ['name' => 'Gomati', 'state_id' => $this->getStateId('Tripura')] ,
            ['name' => 'Khowai', 'state_id' => $this->getStateId('Tripura')] ,
            ['name' => 'North Tripura', 'state_id' => $this->getStateId('Tripura')] ,
            ['name' => 'Sepahijala', 'state_id' => $this->getStateId('Tripura')] ,
            ['name' => 'South Tripura', 'state_id' => $this->getStateId('Tripura')] ,
            ['name' => 'Unakoti', 'state_id' => $this->getStateId('Tripura')] ,
            ['name' => 'West Tripura', 'state_id' => $this->getStateId('Tripura')] ,
            // Uttarakhand
            ['name' => 'Almora', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Bageshwar', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Chamoli', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Champawat', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Dehradun', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Haridwar', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Nainital', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Pauri Garhwal', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Pithoragarh', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Rudraprayag', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Tehri Garhwal', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Udham Singh Nagar', 'state_id' => $this->getStateId('Uttarakhand')] ,
            ['name' => 'Uttarkashi', 'state_id' => $this->getStateId('Uttarakhand')] ,
            // Uttar Pradesh
            ['name' => 'Agra', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Aligarh', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Allahabad', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Ambedkar Nagar', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Amethi (Chatrapati Sahuji Mahraj Nagar)', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Amroha (J.P. Nagar)', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Auraiya', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Azamgarh', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Baghpat', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Bahraich', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Ballia', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Balrampur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Banda', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Barabanki', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Bareilly', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Basti', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Bhadohi', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Bijnor', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Budaun', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Bulandshahr', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Chandauli', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Chitrakoot', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Deoria', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Etah', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Etawah', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Faizabad', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Farrukhabad', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Fatehpur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Firozabad', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Gautam Buddha Nagar', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Ghaziabad', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Ghazipur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Gonda', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Gorakhpur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Hamirpur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Hapur (Panchsheel Nagar)', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Hardoi', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Hathras', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Jalaun', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Jaunpur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Jhansi', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Kannauj', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Kanpur Dehat', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Kanpur Nagar', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Kanshiram Nagar (Kasganj)', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Kaushambi', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Kushinagar (Padrauna)', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Lakhimpur - Kheri', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Lalitpur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Lucknow', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Maharajganj', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Mahoba', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Mainpuri', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Mathura', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Mau', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Meerut', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Mirzapur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Moradabad', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Muzaffarnagar', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Pilibhit', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Pratapgarh', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'RaeBareli', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Rampur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Saharanpur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Sambhal (Bhim Nagar)', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Sant Kabir Nagar', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Shahjahanpur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Shamali (Prabuddh Nagar)', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Shravasti', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Siddharth Nagar', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Sitapur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Sonbhadra', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Sultanpur', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Unnao', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            ['name' => 'Varanasi', 'state_id' => $this->getStateId('Uttar Pradesh')] ,
            // West Bengal
            ['name' => 'Alipurduar', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Bankura', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Birbhum', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Burdwan (Bardhaman)', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Cooch Behar', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Dakshin Dinajpur (South Dinajpur)', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Darjeeling', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Hooghly', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Howrah', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Jalpaiguri', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Kalimpong', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Kolkata', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Malda', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Murshidabad', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Nadia', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'North 24 Parganas', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Paschim Medinipur (West Medinipur)', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Purba Medinipur (East Medinipur)', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Purulia', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'South 24 Parganas', 'state_id' => $this->getStateId('West Bengal')] ,
            ['name' => 'Uttar Dinajpur (North Dinajpur)', 'state_id' => $this->getStateId('West Bengal')] ,
        ];

        DB::table('districts')->insert($districts);
    }

    private function getStateId($stateName)
    {
        return DB::table('states')->where('name', $stateName)->value('id');
    }
}

