<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'country_code' => '91',
                'phone_number' => '0000000000',
                'first_name' => 'Divyadham',
                'last_name' => 'System',
                'profile_image' => '',
                'is_verified' => '1',
                'email' => 'divyadham@admin.com',
                'occupation' => 'System Admin',
                'campany_name' => 'Divyadham',
                'address' => 'Village Office',
                'city' => 'Village City',
                'state' => 'State',
                'country' => 'India',
                'zipcode' => '123456',
                'status' => '1',
                'device_type' => 'web',
                'device_token' => '',
            ],
            [
                'country_code' => '91',
                'phone_number' => '9876543210',
                'first_name' => 'Rajesh',
                'last_name' => 'Kumar',
                'profile_image' => '',
                'is_verified' => '1',
                'email' => 'rajesh@example.com',
                'occupation' => 'Farmer',
                'campany_name' => '',
                'address' => 'House No. 123',
                'city' => 'Village City',
                'state' => 'State',
                'country' => 'India',
                'zipcode' => '123456',
                'status' => '1',
                'device_type' => 'android',
                'device_token' => '',
            ],
            [
                'country_code' => '91',
                'phone_number' => '9876543211',
                'first_name' => 'Priya',
                'last_name' => 'Sharma',
                'profile_image' => '',
                'is_verified' => '1',
                'email' => 'priya@example.com',
                'occupation' => 'Teacher',
                'campany_name' => 'Village School',
                'address' => 'House No. 456',
                'city' => 'Village City',
                'state' => 'State',
                'country' => 'India',
                'zipcode' => '123456',
                'status' => '1',
                'device_type' => 'ios',
                'device_token' => '',
            ],
            [
                'country_code' => '91',
                'phone_number' => '9876543212',
                'first_name' => 'Amit',
                'last_name' => 'Patel',
                'profile_image' => '',
                'is_verified' => '0',
                'email' => 'amit@example.com',
                'occupation' => 'Businessman',
                'campany_name' => 'Patel Stores',
                'address' => 'Shop No. 789',
                'city' => 'Village City',
                'state' => 'State',
                'country' => 'India',
                'zipcode' => '123456',
                'status' => '1',
                'device_type' => 'android',
                'device_token' => '',
            ],
            [
                'country_code' => '91',
                'phone_number' => '9876543213',
                'first_name' => 'Sunita',
                'last_name' => 'Singh',
                'profile_image' => '',
                'is_verified' => '1',
                'email' => 'sunita@example.com',
                'occupation' => 'Nurse',
                'campany_name' => 'Health Center',
                'address' => 'House No. 321',
                'city' => 'Village City',
                'state' => 'State',
                'country' => 'India',
                'zipcode' => '123456',
                'status' => '1',
                'device_type' => 'ios',
                'device_token' => '',
            ],
            [
                'country_code' => '91',
                'phone_number' => '9876543214',
                'first_name' => 'Vikram',
                'last_name' => 'Yadav',
                'profile_image' => '',
                'is_verified' => '1',
                'email' => 'vikram@example.com',
                'occupation' => 'Engineer',
                'campany_name' => 'Tech Solutions',
                'address' => 'House No. 654',
                'city' => 'Village City',
                'state' => 'State',
                'country' => 'India',
                'zipcode' => '123456',
                'status' => '1',
                'device_type' => 'web',
                'device_token' => '',
            ],
            [
                'country_code' => '91',
                'phone_number' => '9876543215',
                'first_name' => 'Meera',
                'last_name' => 'Gupta',
                'profile_image' => '',
                'is_verified' => '0',
                'email' => 'meera@example.com',
                'occupation' => 'Student',
                'campany_name' => '',
                'address' => 'House No. 987',
                'city' => 'Village City',
                'state' => 'State',
                'country' => 'India',
                'zipcode' => '123456',
                'status' => '1',
                'device_type' => 'android',
                'device_token' => '',
            ],
            [
                'country_code' => '91',
                'phone_number' => '9876543216',
                'first_name' => 'Ramesh',
                'last_name' => 'Verma',
                'profile_image' => '',
                'is_verified' => '1',
                'email' => 'ramesh@example.com',
                'occupation' => 'Doctor',
                'campany_name' => 'Village Clinic',
                'address' => 'Clinic No. 1',
                'city' => 'Village City',
                'state' => 'State',
                'country' => 'India',
                'zipcode' => '123456',
                'status' => '1',
                'device_type' => 'ios',
                'device_token' => '',
            ],
            [
                'country_code' => '91',
                'phone_number' => '9876543217',
                'first_name' => 'Kavita',
                'last_name' => 'Joshi',
                'profile_image' => '',
                'is_verified' => '1',
                'email' => 'kavita@example.com',
                'occupation' => 'Social Worker',
                'campany_name' => 'NGO',
                'address' => 'House No. 147',
                'city' => 'Village City',
                'state' => 'State',
                'country' => 'India',
                'zipcode' => '123456',
                'status' => '1',
                'device_type' => 'android',
                'device_token' => '',
            ],
            [
                'country_code' => '91',
                'phone_number' => '9876543218',
                'first_name' => 'Suresh',
                'last_name' => 'Reddy',
                'profile_image' => '',
                'is_verified' => '1',
                'email' => 'suresh@example.com',
                'occupation' => 'Shopkeeper',
                'campany_name' => 'Reddy General Store',
                'address' => 'Shop No. 258',
                'city' => 'Village City',
                'state' => 'State',
                'country' => 'India',
                'zipcode' => '123456',
                'status' => '1',
                'device_type' => 'web',
                'device_token' => '',
            ],
        ];

        DB::table('users')->insert($users);
    }
}
